# vim: set ft=dockerfile :

FROM  ubuntu

MAINTAINER crane

CMD echo 'docker run'

USER crane

# WORKDIR

# VOLUME

# ARG

# RUN [, ]
# RUN
# RUN

# ENTRYPOINT

# ADD
# COPY

# ENV

# EXPOSE 22

# ONBUILD

# SHELL
