# vim: set ft=dockerfile :

FROM  ubuntu

MAINTAINER crane

CMD echo 'docker run'

USER root

# WORKDIR

# VOLUME

# ARG

# RUN [, ]
# RUN
# RUN

#ENTRYPOINT /bin/bash -c

# ADD
# COPY

# ENV

# EXPOSE 22

# ONBUILD

# SHELL
